sudo: required

language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

script:
- cargo install cargo-kcov
- cargo test --no-run


cache:
    apt: true
    directories:
        - target/debug/deps
        - target/debug/build


addons:
  apt:
    packages:
      - cmake
      - g++
      - pkg-config
      - jq
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - libiberty-dev


after_success: |
    [ $TRAVIS_RUST_VERSION = stable ] &&
    wget https://github.com/shaneutt/kcov/archive/master.tar.gz &&
    tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build && cmake .. && make && make install DESTDIR=../tmp && cd ../.. &&
    ls target/debug && 
    for PROGRAM_NAME in $(ls target/debug/simxiv_*); do; ./kcov-master/tmp/usr/local/bin/kcov --exclude-pattern=/.cargo target/kcov_$PROGRAM_NAME target/debug/$PROGRAM_NAME; done && 
    ./kcov-master/tmp/usr/local/bin/kcov --exclude-pattern=/.cargo --merge target/kcov_* target/debug/simxiv_prelude*
